'use client';

import React, { useState } from 'react';
import { AcademicPaper, LiteratureReview } from '@/types/academic';
import { X, Copy, Check, Download, FileText, Code2 } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  papers: AcademicPaper[];
  review: LiteratureReview | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  papers,
  review,
}) => {
  const [activeTab, setActiveTab] = useState<'bibtex' | 'markdown'>('markdown');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  // Generate BibTeX string
  const generateBibtex = () => {
    return papers
      .map((p) => {
        const firstAuthor = p.authors[0]?.split(' ').pop()?.toLowerCase() || 'author';
        const citeKey = `${firstAuthor}${p.year}${p.id.slice(0, 4)}`;
        return `@article{${citeKey},
  title = {${p.title}},
  author = {${p.authors.join(' and ')}},
  year = {${p.year}},
  journal = {${p.venue}},
  abstract = {${p.abstract}}
}`;
      })
      .join('\n\n');
  };

  // Generate Markdown string
  const generateMarkdown = () => {
    if (!review) return `# Academic Corpus Overview\n\nTotal papers: ${papers.length}`;

    let md = `# ${review.title}\n\n`;
    md += `*Generated by IBM Watsonx Research Agent (Granite 3.0)*  \n`;
    md += `*Date: ${review.generatedAt}*\n\n`;
    md += `## Executive Summary\n${review.executiveSummary}\n\n`;

    md += `## Comparative Benchmarks\n`;
    md += `| System | Benchmark | Score | Latency |\n|---|---|---|---|\n`;
    review.benchmarkTable.forEach((b) => {
      md += `| ${b.system} | ${b.benchmark} | ${b.accuracy} | ${b.latency} |\n`;
    });
    md += `\n`;

    review.sections.forEach((s) => {
      md += `## ${s.title}\n${s.content}\n\n`;
    });

    md += `## Open Challenges\n`;
    review.openChallenges.forEach((c) => {
      md += `- ${c}\n`;
    });
    md += `\n`;

    md += `## Future Directions\n`;
    review.futureDirections.forEach((f) => {
      md += `- ${f}\n`;
    });

    return md;
  };

  const currentContent = activeTab === 'bibtex' ? generateBibtex() : generateMarkdown();

  const handleCopy = () => {
    navigator.clipboard.writeText(currentContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = activeTab === 'bibtex' ? 'references.bib' : 'literature-review.md';
    const blob = new Blob([currentContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-stone-900/50 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white border border-claude-border rounded-2xl w-full max-w-2xl overflow-hidden shadow-claude-lg flex flex-col max-h-[85vh] animate-in fade-in zoom-in-95">
        {/* Header */}
        <div className="p-4 border-b border-claude-border flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <span className="text-xs font-mono font-semibold uppercase tracking-wider text-claude-text">
              Export Academic Synthesis
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-claude-muted hover:text-claude-text hover:bg-claude-subtle rounded-lg transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="px-4 pt-3 flex items-center justify-between border-b border-claude-border bg-claude-subtle/50">
          <div className="flex space-x-2">
            <button
              onClick={() => setActiveTab('markdown')}
              className={`flex items-center space-x-1.5 px-3 py-1.5 text-xs font-mono border-b-2 transition-all ${
                activeTab === 'markdown'
                  ? 'border-claude-terracotta text-claude-terracotta font-semibold'
                  : 'border-transparent text-claude-muted hover:text-claude-text'
              }`}
            >
              <FileText className="w-3.5 h-3.5 text-claude-terracotta" />
              <span>Markdown (.md)</span>
            </button>
            <button
              onClick={() => setActiveTab('bibtex')}
              className={`flex items-center space-x-1.5 px-3 py-1.5 text-xs font-mono border-b-2 transition-all ${
                activeTab === 'bibtex'
                  ? 'border-claude-orange text-claude-orange font-semibold'
                  : 'border-transparent text-claude-muted hover:text-claude-text'
              }`}
            >
              <Code2 className="w-3.5 h-3.5 text-claude-orange" />
              <span>BibTeX (.bib)</span>
            </button>
          </div>

          <div className="flex items-center space-x-2 pb-2">
            <button
              onClick={handleCopy}
              className="flex items-center space-x-1 px-2.5 py-1 bg-white border border-claude-border hover:border-claude-terracotta/40 text-claude-text rounded-lg text-xs font-mono transition-colors shadow-xs"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-stone-400" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center space-x-1 px-2.5 py-1 bg-claude-terracotta hover:bg-claude-terracotta-hover text-white rounded-lg text-xs font-mono transition-colors shadow-xs shadow-claude-terracotta/20"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download</span>
            </button>
          </div>
        </div>

        {/* Code Content Preview */}
        <div className="flex-1 overflow-y-auto p-4 bg-claude-subtle/40 font-mono text-[11px] text-claude-text leading-relaxed selection:bg-claude-terracotta-light selection:text-claude-terracotta">
          <pre className="whitespace-pre-wrap">{currentContent}</pre>
        </div>
      </div>
    </div>
  );
};
